### ISSUE TITLE
Model checkpoints

### ISSUE THREAD

**Issue by jiaqixuac** [taco-group/MWFormer#1]
Thank you for sharing your great work.
May I know if the checkpoints are available?

**Comment by zrx2000** [comment]
Hi, we have uploaded the model weights here: [Google Drive link](https://drive.google.com/file/d/12tP7I1wm7sSI7ZlLBZz78tlrIV-JhsWP/view?usp=sharing). Thank you!

**Comment by jiaqixuac** [comment]
Thank you for sharing the checkpoints.
I would like to know the total batch size and the type of GPU you used for training. I noticed that the batch size is 10 + 11 + 11 for a single GPU, but I am unable to fit it into a 12GB GPU.

**Comment by zrx2000** [comment]
We trained the model on two RTX 3090 GPUs (each with 24G memory). You could try reducing the number of channels or the batch size.

**Comment by Chonn18** [comment]
> Thank you for sharing your great work. May I know if the checkpoints are available?

Hi, I'm also interested in this repo but am having dependency issues. I've seen others have similar problems, and the author hasn't clarified. Were you able to install it, and if so, could you share the necessary dependencies?
